<?php

namespace ContainerFxJFdcG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9gx2998Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9gx2998' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9gx2998'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chatMessageRepository' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'chatMessageRepository' => 'App\\Repository\\ChatMessageRepository',
            'eventRepository' => 'App\\Repository\\EventRepository',
        ]);
    }
}
