<?php

namespace Container5jnZ8ju;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLOe0afService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OLOe0af' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OLOe0af'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DashboardController::categories' => ['privates', '.service_locator.Fq26VWZ', 'get_ServiceLocator_Fq26VWZService', true],
            'App\\Controller\\DashboardController::mestags' => ['privates', '.service_locator.HtrqSaY', 'get_ServiceLocator_HtrqSaYService', true],
            'App\\Controller\\DashboardController::saveTags' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\EventController::AfficheEvent' => ['privates', '.service_locator.stp36i_', 'get_ServiceLocator_Stp36iService', true],
            'App\\Controller\\EventController::EventToBDD' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController::postChatMessage' => ['privates', '.service_locator..KTwfTE', 'get_ServiceLocator__KTwfTEService', true],
            'App\\Controller\\EventController::show' => ['privates', '.service_locator.9gx2998', 'get_ServiceLocator_9gx2998Service', true],
            'App\\Controller\\LoginController::avatar' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.H2lArlK', 'get_ServiceLocator_H2lArlKService', true],
            'App\\Controller\\LoginController::profil' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\LoginController::tags' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.yy.Upc_', 'get_ServiceLocator_Yy_UpcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\DashboardController:categories' => ['privates', '.service_locator.Fq26VWZ', 'get_ServiceLocator_Fq26VWZService', true],
            'App\\Controller\\DashboardController:mestags' => ['privates', '.service_locator.HtrqSaY', 'get_ServiceLocator_HtrqSaYService', true],
            'App\\Controller\\DashboardController:saveTags' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\EventController:AfficheEvent' => ['privates', '.service_locator.stp36i_', 'get_ServiceLocator_Stp36iService', true],
            'App\\Controller\\EventController:EventToBDD' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController:postChatMessage' => ['privates', '.service_locator..KTwfTE', 'get_ServiceLocator__KTwfTEService', true],
            'App\\Controller\\EventController:show' => ['privates', '.service_locator.9gx2998', 'get_ServiceLocator_9gx2998Service', true],
            'App\\Controller\\LoginController:avatar' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.H2lArlK', 'get_ServiceLocator_H2lArlKService', true],
            'App\\Controller\\LoginController:profil' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\LoginController:tags' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.yy.Upc_', 'get_ServiceLocator_Yy_UpcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\DashboardController::categories' => '?',
            'App\\Controller\\DashboardController::mestags' => '?',
            'App\\Controller\\DashboardController::saveTags' => '?',
            'App\\Controller\\EventController::AfficheEvent' => '?',
            'App\\Controller\\EventController::EventToBDD' => '?',
            'App\\Controller\\EventController::postChatMessage' => '?',
            'App\\Controller\\EventController::show' => '?',
            'App\\Controller\\LoginController::avatar' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\LoginController::profil' => '?',
            'App\\Controller\\LoginController::tags' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DashboardController:categories' => '?',
            'App\\Controller\\DashboardController:mestags' => '?',
            'App\\Controller\\DashboardController:saveTags' => '?',
            'App\\Controller\\EventController:AfficheEvent' => '?',
            'App\\Controller\\EventController:EventToBDD' => '?',
            'App\\Controller\\EventController:postChatMessage' => '?',
            'App\\Controller\\EventController:show' => '?',
            'App\\Controller\\LoginController:avatar' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\LoginController:profil' => '?',
            'App\\Controller\\LoginController:tags' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
