<?php

namespace Container5jnZ8ju;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__KTwfTEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..KTwfTE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..KTwfTE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chatMessageRepository' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'userRepository' => ['services', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'chatMessageRepository' => 'App\\Repository\\ChatMessageRepository',
            'eventRepository' => 'App\\Repository\\EventRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
