<?php

namespace Container5jnZ8ju;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Stp36iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.stp36i_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.stp36i_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'callApiService' => ['privates', 'App\\Service\\CallApiService', 'getCallApiServiceService', true],
            'dm' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'callApiService' => 'App\\Service\\CallApiService',
            'dm' => '?',
            'eventRepository' => 'App\\Repository\\EventRepository',
        ]);
    }
}
