<?php

namespace Container5jnZ8ju;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagsFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TagsFormType' shared autowired service.
     *
     * @return \App\Form\TagsFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TagsFormType.php';

        return $container->privates['App\\Form\\TagsFormType'] = new \App\Form\TagsFormType();
    }
}
