<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentEventsHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['startDate'])) {
            $value = $data['startDate'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['startDate']->setValue($document, clone $return);
            $hydratedData['startDate'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['endDate'])) {
            $value = $data['endDate'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['endDate']->setValue($document, clone $return);
            $hydratedData['endDate'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description']) || (! empty($this->class->fieldMappings['description']['nullable']) && array_key_exists('description', $data))) {
            $value = $data['description'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['description']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['picture']) || (! empty($this->class->fieldMappings['picture']['nullable']) && array_key_exists('picture', $data))) {
            $value = $data['picture'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['picture']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['picture']->setValue($document, $return);
            $hydratedData['picture'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['place']) || (! empty($this->class->fieldMappings['place']['nullable']) && array_key_exists('place', $data))) {
            $value = $data['place'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['place']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['place']->setValue($document, $return);
            $hydratedData['place'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['planner']) || (! empty($this->class->fieldMappings['planner']['nullable']) && array_key_exists('planner', $data))) {
            $value = $data['planner'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['planner']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['planner']->setValue($document, $return);
            $hydratedData['planner'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['title']) || (! empty($this->class->fieldMappings['title']['nullable']) && array_key_exists('title', $data))) {
            $value = $data['title'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['title']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['address']) || (! empty($this->class->fieldMappings['address']['nullable']) && array_key_exists('address', $data))) {
            $value = $data['address'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['address']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['address']->setValue($document, $return);
            $hydratedData['address'] = $return;
        }
        return $hydratedData;
    }
}