<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5jnZ8ju\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5jnZ8ju/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5jnZ8ju.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5jnZ8ju\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5jnZ8ju\App_KernelDevDebugContainer([
    'container.build_hash' => '5jnZ8ju',
    'container.build_id' => 'cea03a62',
    'container.build_time' => 1690463745,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5jnZ8ju');
