<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxJFdcG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxJFdcG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxJFdcG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxJFdcG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxJFdcG\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxJFdcG',
    'container.build_id' => '817a2586',
    'container.build_time' => 1690532823,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxJFdcG');
