<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'get_user_tags' => [[], ['_controller' => 'App\\Controller\\DashboardController::getUserTags'], [], [['text', '/get_user_tags']], [], [], []],
    'app_dashboard_categories' => [[], ['_controller' => 'App\\Controller\\DashboardController::categories'], [], [['text', '/categories']], [], [], []],
    'app_dashboard_mestags' => [[], ['_controller' => 'App\\Controller\\DashboardController::mestags'], [], [['text', '/mestags']], [], [], []],
    'app_dashboard_mesevents' => [[], ['_controller' => 'App\\Controller\\DashboardController::mesevents'], [], [['text', '/mesevents']], [], [], []],
    'app_dashboard_mestags_save' => [['jsontags'], ['_controller' => 'App\\Controller\\DashboardController::saveTags'], [], [['variable', '/', '[^/]++', 'jsontags', true], ['text', '/mestags/save']], [], [], []],
    'app_event_affichage' => [[], ['_controller' => 'App\\Controller\\EventController::AfficheEvent'], [], [['text', '/event/affichage']], [], [], []],
    'app_event_mesevents' => [[], ['_controller' => 'App\\Controller\\EventController::mesevents'], [], [['text', '/event/mesevents']], [], [], []],
    'app_event_bdd' => [[], ['_controller' => 'App\\Controller\\EventController::EventToBDD'], [], [['text', '/event/to_bdd']], [], [], []],
    'app_event_show' => [['eventId'], ['_controller' => 'App\\Controller\\EventController::show'], [], [['variable', '/', '[^/]++', 'eventId', true], ['text', '/event']], [], [], []],
    'app_event_post_chat_message' => [['eventId'], ['_controller' => 'App\\Controller\\EventController::postChatMessage'], [], [['text', '/post_chat_message'], ['variable', '/', '[^/]++', 'eventId', true], ['text', '/event']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_home_presentation' => [[], ['_controller' => 'App\\Controller\\HomeController::presentation'], [], [['text', '/homepresentation']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login/']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/login/logout']], [], [], []],
    'app_profil' => [[], ['_controller' => 'App\\Controller\\LoginController::profil'], [], [['text', '/login/profil']], [], [], []],
    'app_login_avatar' => [[], ['_controller' => 'App\\Controller\\LoginController::avatar'], [], [['text', '/login/avatar']], [], [], []],
    'app_tags' => [[], ['_controller' => 'App\\Controller\\LoginController::tags'], [], [['text', '/login/tags']], [], [], []],
    'app_registration' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/registration']], [], [], []],
    'app_event_categories' => [[], ['_controller' => 'App\\Controller\\EventController::categories'], [], [['text', '/categories']], [], [], []],
    'app_event_calendar' => [[], ['_controller' => 'App\\Controller\\EventController::calendar'], [], [['text', '/calendar']], [], [], []],
];
