<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'app_event' => [[], ['_controller' => 'App\\Controller\\EventController::index'], [], [['text', '/event/']], [], [], []],
    'app_event_show' => [['eventId'], ['_controller' => 'App\\Controller\\EventController::show'], [], [['variable', '/', '[^/]++', 'eventId', true], ['text', '/event']], [], [], []],
    'app_event_post_chat_message' => [['eventId'], ['_controller' => 'App\\Controller\\EventController::postChatMessage'], [], [['text', '/post_chat_message'], ['variable', '/', '[^/]++', 'eventId', true], ['text', '/event']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home/']], [], [], []],
    'app_home_presentation' => [[], ['_controller' => 'App\\Controller\\HomeController::presentation'], [], [['text', '/home/homepresentation']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_profil' => [[], ['_controller' => 'App\\Controller\\LoginController::profil'], [], [['text', '/profil']], [], [], []],
    'app_login_avatar' => [[], ['_controller' => 'App\\Controller\\LoginController::avatar'], [], [['text', '/loginavatar']], [], [], []],
    'app_tags' => [[], ['_controller' => 'App\\Controller\\LoginController::tags'], [], [['text', '/tags']], [], [], []],
    'app_registration' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/registration']], [], [], []],
    'registration_success' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register_success'], [], [['text', '/registration-success']], [], [], []],
    'registration_error' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register_error'], [], [['text', '/registration-error']], [], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], [], []],
    'app_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], [], []],
    'app_event_categories' => [[], ['_controller' => 'App\\Controller\\EventController::categories'], [], [['text', '/categories']], [], [], []],
];
