<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'app_dashboard_mainboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::categories'], [], [['text', '/mainboard']], [], [], []],
    'app_event' => [[], ['_controller' => 'App\\Controller\\EventController::index'], [], [['text', '/event/']], [], [], []],
    'app_event_mestags' => [[], ['_controller' => 'App\\Controller\\EventController::mestags'], [], [['text', '/event/mestags']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login/']], [], [], []],
    'app_registration' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/registration']], [], [], []],
    'registration_success' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register_success'], [], [['text', '/registration-success']], [], [], []],
    'registration_error' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register_error'], [], [['text', '/registration-error']], [], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], [], []],
    'app_participer' => [[], ['_controller' => 'App\\Controller\\TestController::participer'], [], [['text', '/participer']], [], [], []],
    'app_event_categories' => [[], ['_controller' => 'App\\Controller\\EventController::categories'], [], [['text', '/categories']], [], [], []],
    'app_event_calendar' => [[], ['_controller' => 'App\\Controller\\EventController::calendar'], [], [['text', '/calendar']], [], [], []],
];
