<?php

namespace ContainerNCPmvKT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HX5RszoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hX5Rszo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hX5Rszo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EventController::categories' => ['privates', '.service_locator.Fq26VWZ', 'get_ServiceLocator_Fq26VWZService', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController::testApi' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.yy.Upc_', 'get_ServiceLocator_Yy_UpcService', true],
            'App\\Controller\\RegistrationController::register_success' => ['privates', '.service_locator.yy.Upc_', 'get_ServiceLocator_Yy_UpcService', true],
            'App\\Controller\\TestController::index' => ['privates', '.service_locator.IdwyOIE', 'get_ServiceLocator_IdwyOIEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\EventController:categories' => ['privates', '.service_locator.Fq26VWZ', 'get_ServiceLocator_Fq26VWZService', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\EventController:testApi' => ['privates', '.service_locator.37hY7K.', 'get_ServiceLocator_37hY7K_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.yy.Upc_', 'get_ServiceLocator_Yy_UpcService', true],
            'App\\Controller\\RegistrationController:register_success' => ['privates', '.service_locator.yy.Upc_', 'get_ServiceLocator_Yy_UpcService', true],
            'App\\Controller\\TestController:index' => ['privates', '.service_locator.IdwyOIE', 'get_ServiceLocator_IdwyOIEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\EventController::categories' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Controller\\EventController::testApi' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::register_success' => '?',
            'App\\Controller\\TestController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EventController:categories' => '?',
            'App\\Controller\\EventController:index' => '?',
            'App\\Controller\\EventController:testApi' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:register_success' => '?',
            'App\\Controller\\TestController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
