<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSHnD68h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSHnD68h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSHnD68h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSHnD68h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSHnD68h\App_KernelDevDebugContainer([
    'container.build_hash' => 'SHnD68h',
    'container.build_id' => 'b628e5ef',
    'container.build_time' => 1689080850,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSHnD68h');
