<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFyxxyx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFyxxyx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVFyxxyx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVFyxxyx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVFyxxyx\App_KernelDevDebugContainer([
    'container.build_hash' => 'VFyxxyx',
    'container.build_id' => 'f900ac10',
    'container.build_time' => 1689150642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVFyxxyx');
