<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKPwxqSz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKPwxqSz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKPwxqSz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKPwxqSz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKPwxqSz\App_KernelDevDebugContainer([
    'container.build_hash' => 'KPwxqSz',
    'container.build_id' => '6dbe1295',
    'container.build_time' => 1689079440,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKPwxqSz');
